### ISSUE TITLE
Mark not set

### ISSUE THREAD

**Issue by samcdavid** [hhsnopek/vim-sugarss#1]
When editing a SugarSS file, I receive the following error in vim:

```
Error detected while processing /path/to/.vim/bundle/vim-sugarss/syntax/sugarss.vim:
line   37:
E20: Mark not set
line   39:
E20: Mark not set
Press ENTER or type command to continue
```

It looks like there are some comments in there that need to be changed from single quotes to double quotes. At least that resolves the issue for me. Would you accept a PR to fix this issue?

**Comment by hhsnopek** [comment]
I'll always accept a PR! 😄 
It looks like my testing strings got inside here, could you go ahead and remove those lines instead of making them true comments?

I believe these are the offending lines

```
'hell'
"hell"
'hell-o'
```

**Comment by samcdavid** [comment]
Yea, those are the ones that I had commented out. I can go ahead and yank them out.
